def _broadcast_to_qq(self, message):
    # Existing logic here...
    target = {"817621853": "group"}
    processed_info = ProcessedInfo(message=message, target=target)
    # Continue with the rest of the method logic using processed_info...
